# Generated by Django 5.2.1 on 2025-05-09 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('clay_courts', models.PositiveIntegerField(default=0)),
                ('grass_courts', models.PositiveIntegerField(default=0)),
                ('hard_courts', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surface', models.CharField(choices=[('Clay', 'Clay'), ('Grass', 'Grass'), ('Hard', 'Hard')], max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='rezervace.location')),
            ],
        ),
    ]
