# Generated by Django 5.2.1 on 2025-05-10 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0003_alter_reservation_court_alter_reservation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rezervace.location', verbose_name='Location'),
        ),
    ]
