# Generated by Django 5.2.1 on 2025-05-10 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0005_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tournament Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacity')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='rezervace.location', verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('birth_date', models.DateField(verbose_name='Date of Birth')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='rezervace.tournament', verbose_name='Tournament')),
            ],
        ),
    ]
