# Generated by Django 5.2.1 on 2025-05-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0006_tournament_tournamentparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], verbose_name='Rating'),
        ),
    ]
