# Generated by Django 5.2.1 on 2025-05-11 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0007_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezervace.location', verbose_name='Location'),
        ),
    ]
